language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew reinstall xctool
xcode_sdk:
  - iphonesimulator9.2
#  - appletvsimulator9.1
script:
  - xcodebuild -showsdks
  - xctool -project Project/Player.xcodeproj -scheme 'Debug - iOS' -sdk iphonesimulator9.2 build analyze
#  - xctool -project Project/Player.xcodeproj -scheme 'Debug - tvOS' -sdk appletvsimulator9.1 build analyze
